name: Car Rental Webservice

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI_Car_Rental_Webservice:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Update Composer
        run: composer update

      - name: Install Dependencies
        run: composer install --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Start Server
        run: php artisan serve --no-interaction &

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: newman run tests/postman/Car_Rental.postman_collection.json

      - name: Execute Unit and Feature tests via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test

      - name: Install Taurus
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install bzt

      - name: Run JMeter tests
        run: bzt tests/jmeter/Car_Rental_Service.jmx
