name: Car Rental Webservice

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

services:
  mysql:
    image: mysql:latest
    env:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_rental
    ports:
      - 3306:3306
    options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Update composer
        run: composer update

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Start Server
        run: php artisan serve &

      - name: Install Newman
        run: npm install -g newman

      - name: Postman tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: mysql
          DB_PORT: 3306
          DB_DATABASE: car_rental
          DB_USERNAME: root
          DB_PASSWORD: root
        run: newman run tests/postman/Car_Rental.postman_collection.json

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_HOST: mysql
          DB_PORT: 3306
          DB_DATABASE: car_rental
          DB_USERNAME: root
          DB_PASSWORD: root
        run: php artisan test

      - name: Install Taurus
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install bzt

      - name: Run JMeter tests
        run: bzt tests/jmeter/Car_Rental_Service.jmx
